/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as variablesSol from "./variables.sol";
export type { variablesSol };
export type { Counter } from "./Counter";
