/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dao from "./DAO";
export type { dao };
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as erc721 from "./ERC721";
export type { erc721 };
import type * as variablesSol from "./variables.sol";
export type { variablesSol };
export type { Counter } from "./Counter";
