/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoSol from "./dao.sol";
export type { daoSol };
import type * as projSol from "./proj.sol";
export type { projSol };
