/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721Sol from "./ERC721.sol";
export type { erc721Sol };
import type * as metadataSol from "./metadata.sol";
export type { metadataSol };
import type * as metadata1Sol from "./metadata1.sol";
export type { metadata1Sol };
import type * as ownerShipTransferSol from "./ownerShip&transfer.sol";
export type { ownerShipTransferSol };
