/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as variablesSol from "./variables.sol";
export type { variablesSol };
export type { Counter } from "./Counter";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export type { MyContract } from "./variables.sol/MyContract";
export { MyContract__factory } from "./factories/variables.sol/MyContract__factory";
